# Aplicação
spring.application.name=LactareAPI

# Banco de Dados Oracle (FIAP)

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tratamento de Erros da API
server.error.include-stacktrace=never
server.error.include-message=always
